  services:
    db:
      container_name: db_bootcamp_sql
      image: postgres:latest
      environment:
        POSTGRES_DB: northwind
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - postgresql_bin:/usr/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data
        - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
        - ./files:/files
      ports:
        - 55432:5432
      networks:
        - db

    pgadmin:
      container_name: pgadmin_bootcamp_sql
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: postgres@postgres.com.br
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_LISTEN_PORT: 5050
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - postgresql_bin:/usr/lib/postgresql
        - pgadmin_root_prefs:/root/.pgadmin
        - pgadmin_working_dir:/var/lib/pgadmin
        - ./files:/files
      ports:
        - 55050:5050
      networks:
        - db

  networks:
    db:
      driver: bridge

  volumes:
    pgadmin_root_prefs:
      driver: local
    pgadmin_working_dir:
      driver: local
    postgresql_data:
      driver: local
    postgresql_bin:
      driver: local